name: Build React Native App

on:
  push:
    branches:
      - test_github_actions
    permissions:
      id-token: write
      contents: read
      issues: write
      pull-requests: write

jobs:
  Make_GitHub_Release:
    name: Create Release
    runs-on: macos-latest
    outputs:
      upload_url: ${{ steps.get_upload_url.outputs.result }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 19.6.0

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: adopt

      - name: Install dependencies
        run: npm install

      - name: Install CocoaPods
        run: sudo gem install cocoapods

      - name: Build iOS App
        run: |
          cd ios
          pod install
          xcodebuild -workspace myApp.xcworkspace -scheme myApp -destination 'platform=iOS Simulator,name=iPhone 12' build

      - name: Export IPA
        run: |
          xcodebuild -exportArchive -archivePath myApp.xcarchive -exportPath ios -exportOptionsPlist ExportOptions.plist

      - name: Upload IPA
        uses: actions/upload-artifact@v2
        with:
          name: myApp
          path: myApp.ipa