name: Build React Native App

on:
  push:
    branches:
      - test_github_actions
    permissions:
      id-token: write
      contents: read
      issues: write
      pull-requests: write

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 19.6.0

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: adopt

      - name: Install dependencies
        run: npm install

      - name: Build Android App apk
        run: |
          cd android && ./gradlew assembleRelease --no-daemon

      - name: Create release directory
        run: |
          mkdir -p android/app/build/outputs/apk/release

      - name: Adjust file permissions
        run: |
          chmod -R +rx android/app/build/outputs/apk/release

      - name: Sign App apk
        id: sign_app
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: android/app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
          alias: ${{ secrets.ANDROID_SIGNING_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_SIGNING_STORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_SIGNING_KEY_PASSWORD }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0  # Replace with your valid tag name
          release_name: Release v1.0.0

      - name: Upload APK
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.get_upload_url.outputs.result }}
          asset_path: android/app/build/outputs/apk/release/app-release.apk
          asset_name: app-release.apk
          asset_content_type: application/vnd.android.package-archive