name: Build React Native App

on:
  push:
    branches:
      - test_github_actions

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 19.6.0

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: adopt

      - name: Install dependencies
        run: npm install

      - name: Build Android App Bundle
        run: |
          cd android && ./gradlew assembleRelease --no-daemon

      - name: Create release directory
        run: |
          mkdir -p android/app/build/outputs/bundle/release

      - name: Adjust file permissions
        run: |
          chmod -R +rx android/app/build/outputs/bundle/release

      - name: Sign App Bundle
        id: sign_app
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: android/app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
          alias: ${{ secrets.ANDROID_SIGNING_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_SIGNING_STORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_SIGNING_KEY_PASSWORD }}